version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis_jogo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  soap-api:
    build:
      context: ./soap
      dockerfile: dockerfile
    container_name: soap
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./soap:/app

  rest-api:
    build:
      context: ./rest
      dockerfile: dockerfile
    container_name: rest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./rest:/app

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - soap-api
      - rest-api
    volumes:
      - ./gateway:/app

volumes:
  redis-data: {}
