version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis_jogo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  soap-api:
    build:
      context: ./soap
      dockerfile: Dockerfile
    container_name: soap_api
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./soap:/app

volumes:
  redis-data:
